version: '3.4'

services:
  graphql-api:
    container_name: 'graphql-api'
    restart: 'always'
    build:
      target: api-gateway
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:3000'
    env_file: ./env/.api-gateway.env

  color-service:
    container_name: 'color-service'
    restart: 'always'
    build:
      target: color
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - graphql-api
    ports:
      - '4001:3000'
    env_file: ./env/.color-service.env

  house-service:
    container_name: 'house-service'
    restart: 'always'
    build:
      target: house
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4002:3000'
    env_file: ./env/.house-service.env

  # rabbitmq:  if you need rabbitmq
  #   container_name: 'rabbitmq'
  #   restart: 'always'
  #   image: rabbitmq:3.8.9-management
  #   ports:
  #     - '15672:15672'
  #   env_file: ./env/.docker-compose.env
